version: '3.8'
services:

    jabirucms-mysql:
        image: mysql:8.0
        container_name: jabirucms-mysql
        volumes:
            - .docker/data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "33076:3306"
        restart: unless-stopped
        networks:
            - jabirucms-net

    jabirucms-php:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        container_name: jabirucms-php
        volumes:
            - .:/var/www
            - ~/.ssh:/root/.ssh
        ports:
            - "8760:80"
        restart: unless-stopped
        networks:
            - jabirucms-net

    jabirucms-redis:
        image: redis:latest
        container_name: jabirucms-redis
        restart: unless-stopped
        networks:
            - jabirucms-net

    jabirucms-mail:
        image: mailhog/mailhog
        container_name: jabirucms-mail
        ports:
            - "8761:8025"
        restart: unless-stopped
        networks:
            - jabirucms-net

networks:
    jabirucms-net:
        name: jabirucms-net

