version: '3.8'
services:

    gottstein-mysql:
        image: mysql:8.0
        volumes:
            - .docker/data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_DATABASE=gottsteinsaunas
            - MYSQL_USER=gottsteinsaunas
            - MYSQL_PASSWORD=secret
        ports:
            - 33806:3306
        restart: always
        networks:
            - gottstein-net

    gottstein-php:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        container_name: gottstein-php
        volumes:
            - .:/var/www
            - ~/.ssh:/root/.ssh
        ports:
            - "8860:80"
        networks:
            - gottstein-net

    gottstein-redis:
        image: redis:latest
        container_name: gottstein-redis
        networks:
            - gottstein-net

    gottstein-mail:
        image: mailhog/mailhog
        container_name: gottstein-mail
        ports:
            - 8861:8025
        networks:
            - gottstein-net

networks:
    gottstein-net:
        name: gottstein-net

