FROM php:8.1-fpm

# Set working directory
WORKDIR /var/www

# Add docker php ext repo
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

# Install php extensions
RUN chmod +x /usr/local/bin/install-php-extensions && sync && \
    install-php-extensions mbstring pdo_pgsql pdo_mysql zip exif pcntl gd memcached redis exif pcntl zip soap

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    unzip \
    git \
    curl \
    lua-zlib-dev \
    libmemcached-dev \
    nginx

# Install supervisor
RUN apt-get install -y supervisor

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# add root to www group
RUN chmod -R +x /var/www/
RUN chmod 777 -R /var/log/
RUN chmod 777 -R /var/www/logs/
RUN chmod 777 -R /var/www/storage/

# Copy nginx/php/supervisor configs
RUN cp .docker/supervisor/default.conf /etc/supervisord.conf
RUN cp .docker/php/php_custom.ini /usr/local/etc/php/conf.d/app.ini
RUN cp .docker/nginx/default.conf /etc/nginx/sites-enabled/default

# PHP Error Log Files
RUN mkdir /var/log/php
RUN touch /var/log/php/errors.log && chmod 777 /var/log/php/errors.log

# Deployment steps
RUN chmod +x /var/www/.docker/run.sh

EXPOSE 80
ENTRYPOINT ["bash","/var/www/.docker/run.sh"]
